# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/soundz',
                'doc_host': 'https://phueac.github.io',
                'git_url': 'https://github.com/phueac/soundz',
                'lib_path': 'soundz'},
  'syms': {'soundz.core': {'soundz.core.foo': ('core.html#foo', 'soundz/core.py')}}}
